name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_1
      id: test_1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_1
        setup-command: ''
        command: pytest tests.py
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_1_RESULTS: "${{steps.test_1.outputs.result}}"
      with:
        runners: test_1
